language: python

jobs:
  include:
  - stage: py2
    python: "2.7"
    install: "pip install flake8"
    script: "flake8 --ignore=F821"

  - stage: py3
    python:
      - "3.3"
      - "3.4"
      - "3.5"
    install: "pip install flake8"
    script: "flake8 --ignore=F821"

  - stage: deploy
    deploy:
      provider: pypi
      distributions: "sdist bdist_wheel"
      user: jtemporal
      password: $PYPI_PASSWORD
      on:
        branch: master
        repo: jtemporal/caipyra
